[FIX] Exception on site scheduler trigger in TYPO3 v9
DMKEBUSINESSGMBH/typo3-mkmailer pull request #12
Opened 2020-03-25 18:41 UTC by paifgx

Fix exception which triggered while trying to run the scheduler in TYPO3 v9 or higher.

UNCAUGHT EXCEPTION FOR VIEW: tx_mkmailer_scheduler_SendMails
Message: InvalidArgumentException: Unable to parse URI: http:///index.php?id=52
Stacktrace: InvalidArgumentException: Unable to parse URI: http:///index.php?id=52 in /var/www/html/vendor/guzzlehttp/psr7/src/Uri.php:71

2020-03-26 10:37 UTC, rengaw83 requested changes
Hi Patrik,

thanks for your work and the pr.

Can you rebase the master please? There are some unittest fixes.

Here are some things we should change:
* why the alias is only translated for TYPO3 8 or lower? i know, its deprecated since 9, but it still exists and can be important for migration projects.
* `$GLOBALS['TYPO3_REQUEST']` is depreceted since TYPO3 9.2 and should not be used for new implementations for TYPO3 9.5 or later. There are a new Sitehandling we should use to get the baseurl. see [AccessingSiteConfiguration Docs](https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/SiteHandling/AccessingSiteConfiguration.html#finding-a-site-object)
* please do not change the gitignore in this context
* please do not change the locallang file access rights in this context.

2020-03-26 11:09 UTC, paifgx commented
Thanks. I will fix it!

2020-03-26 12:11 UTC, paifgx commented
> why the alias is only translated for TYPO3 8 or lower? i know, its deprecated since 9, but it still exists and can be important for migration projects.

 I wrote it into the else statment cause I thought that it did not necessarily have to be executed. I moved it back, before the statement.

> $GLOBALS['TYPO3_REQUEST'] is depreceted since TYPO3 9.2 and should not be used for new implementations for TYPO3 9.5 or later. There are a new Sitehandling we should use to get the baseurl. see AccessingSiteConfiguration Docs

Fixed now

2020-05-25 08:16 UTC, rengaw83 approved these changes

2020-05-25 08:18 UTC, merged